baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Karim's Website"
theme = 'digitalgarden'

[menu]

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/karimzakir02'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/karim-zakir/'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:zakirkarim02@gmail.com'
  weight = 3