baseURL = 'https://karimzakir02.github.io/'
languageCode = 'en-us'
title = "Karim's Website"
theme = 'digitalgarden'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Personal Projects'
  url = '/projects'
  weight = 3
[[menu.main]]
  name = 'Life & Hobbies'
  url = '/life'
  weight = 4

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/karimzakir02'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/karim-zakir/'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:zakirkarim02@gmail.com'
  weight = 3